# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecfbb9d3cf56418034e8a96a616588528c9537b241ddfdbf1725c7987d3b62e8d48892d5cf8949148f6cafa1a4d951576f4640e010389ccc6b424ed6666c3455

test:
  secret_key_base: f9b26cdce560166cf9aec79429cb9e8b784c0c0af39329cd14dc0c12d8ceb816c0ff402d02ff4985bc44d31ca9e7dde60d33e4ad69d13f73a4a4c4a16b9cd2d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
